# Generated by Django 4.1.6 on 2025-01-29 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='images.png', upload_to='')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('DOB', models.CharField(blank=True, max_length=100)),
                ('year_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('content', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.person')),
            ],
        ),
        migrations.CreateModel(
            name='Follow_People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_follow', models.ManyToManyField(related_name='follow', to='layout.person')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.person')),
            ],
        ),
    ]
