# Generated by Django 4.1.6 on 2025-01-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('DOB', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('content', models.CharField(max_length=64)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.person')),
            ],
        ),
    ]
