# Generated by Django 4.1.6 on 2025-01-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_person_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='images.png', upload_to=''),
        ),
    ]
