# Generated by Django 4.1.6 on 2025-01-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_follow', models.ManyToManyField(related_name='follow', to='layout.person')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.person')),
            ],
        ),
    ]
